cargo-features = ["strip"]

[package]
name = "comik"
version = "0.1.0"
edition = "2018"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
iced = { version = "0.3.0", features = ["image"] }
iced_native = "0.4.0"
anyhow = "1.0.44"
image = "0.23.14"
tempfile = "3.2.0"
zip = "0.5.13"
unrar = "0.4.4"
thiserror = "1.0.29"
async-std = "1.10.0"